"""add is_validated to projects

Revision ID: 6612436f12e5
Revises: 2ccd571bd396
Create Date: 2026-08-08 07:17:59.192720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6612436f12e5'
down_revision = '2ccd571bd396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
       batch_op.add_column(sa.Column('is_validated', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_validated')

    # ### end Alembic commands ###
